# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mixaudiofile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mixaudiofile

  pod "mobile-ffmpeg-audio"

  target 'mixaudiofileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mixaudiofileUITests' do
    # Pods for testing
  end

end
